openapi: "3.0.0"
info:
  version: "0.0.1"
  title: Bayes API
  description: Programmatic interface to the MIT ProbComp stack.
  license:
    name: MIT
servers:
  - url: http://bayesapi.probcomp.dev
    description: Local development server
paths:
  /find-peers:
    post:
      summary: Find peer rows
      operationId: findPeers
      description: Find similar rows to the row provided in the request, in the context of the given column.
      tags:
        - peers
      parameters:
        - name: target-row
          in: query
          description: The ID of the base row for finding similar rows.
          required: true
          schema:
            type: integer
            format: int32
        - name: context-column
          in: query
          required: true
          description: The name of the column to be used as context for finding similarlity.
          schema:
            type: string
      responses:
        '200':
          description: A list of rows and their degree of similarity, ordered starting from most similar.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Similarities"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /find-anomalies:
    post:
      summary: Find anomalous rows
      description: Find anomalous rows in the database, given target and context columns.
      operationId: findAnomalies
      tags:
        - anomalies
      parameters:
        - name: context-columns
          in: query
          required: true
          description: The name of the column to be used as context for finding anomalies.
          schema:
            type: array
            items:
              type: string
        - name: target-column
          in: query
          required: true
          description: The name of the column to be used as the target for finding anomalies.
          schema:
            type: string
      responses:
        '200':
          description: An list of rows and their degree of anomalousness, ordered starting from most unlikely.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Anomalies"

  /last-query:
    get:
      summary: Last query
      description: Return data about the last query run.
      operationId: lastQuery
      tags:
        - explanation
      responses:
        '200':
          description: Information about the previous query run.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LastQuery"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /peer-heatmap-data:
    get:
      summary: Heatmap data
      description: Data required to build a heatmap for the query explanation page.
      tags:
        - explanation
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HeatMap"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /anomaly-scatterplot-data:
    get:
      summary: Scatterplot data
      description: Data required for building an anomaly scatterplot
      tags:
        - explanation
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AnomalyScatterplot"

  /table-data:
    get:
      summary: Table data
      description: The entirety of the table data
      tags:
        - table-data
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TableData"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Anomalies:
      description: An array of (row ID, value) pairs, where value is a measure of "anomalousness", ordered by descending value (so the first rows are more anomalous than the later rows).
      type: array
      items:
        $ref: "#/components/schemas/Anomaly"

    Similarities:
      description: An array of (row ID, value) pairs, where value is a measure of similarity, ordered by descending value (so the first rows are more similar to the target row than later ones).
      type: array
      items:
        $ref: "#/components/schemas/Similarity"

    Anomaly:
      description: An element in the list of anomalies. Describes how anomalous a single row is.
      type: object
      properties:
        rowId:
          type: integer
          description: The ID of the row.
        anomalyValue:
          type: number
          format: float
          description: A unitless measure of the degree of anomalousness of the row.

    Similarity:
      description: An element in the list of similarities. Describes how similar a single row is.
      type: object
      properties:
        rowId:
          type: integer
        similarityValue:
          type: number
          format: float

    LastQuery:
      description: Information about the last query run by the system
      type: object
      properties:
        last_query:
          type: string
          description: The BQL of the query itself
        query_type:
          type: string
          description: THe type of the query (peer, anomamly)
        target_column:
          type: string
        context_columns:
          type: string

    HeatMap:
      type: object
      properties:
        top_100:
          description: Heatmap data for the 100 most similar rows
          type: array
          items:
            $ref: "#/components/schemas/SimilarityTriple"
        bottom_100:
          description: Heatmap data for the 100 least similar rows
          type: array
          items:
            $ref: "#/components/schemas/SimilarityTriple"

    # this wants to be a tuple, but OpenAPI wishes tuples out of
    # existance, so we have this tortured array instead. OpenAPI
    # probably wants us to return objects rather than tuples.
    SimilarityTriple:
      type: array
      items:
        oneOf:
          - type: integer
          - type: number
      minItems: 3
      maxItems: 3

    AnomalyScatterplot:
      description: An array of (row ID, value) pairs, where value is a measure of "anomalousness", ordered by descending value (so the first rows are more anomalous than the later rows).
      type: array
      items:
        $ref: "#/components/schemas/Anomaly"

    TableData:
      type: object
      properties:
        columns:
          type: array
          items:
            type: string
        data:
          type: array
          items:
            $ref: "#/components/schemas/TableDataRow"

    TableDataRow:
      type: array
      items:
        oneOf:
          - type: integer
          - type: number
          - type: string

    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
