bdb_file: database.bdb
loom_path: /replace/with/absolute/path
table_name: counties
population_name: counties
log_level: DEBUG
backend: cgpm

history:
    file: history.pickle
    similarity_file: similarity-history.pickle
    anomaly_file: anomaly-file.pickle

gunicorn:
    bind: 0.0.0.0:5000
    workers: 1
    timeout: 30
    reload: True
