bdb_file: database.bdb
table_name: counties
population_name: counties
log_level: DEBUG

history:
    file: history.pickle

gunicorn:
    bind: 0.0.0.0:5000
    workers: 1
    timeout: 30
    reload: True
