version: "3"
networks:
  nginx_probcomp:
    external:
      name: nginx_probcomp

services:
  app:
    build: .
    networks:
      default:
      nginx_probcomp:
        aliases:
          - bayesapi
    environment:
      CONFIG_FILE_PATH: 'config.yaml'
      HTTPS_METHOD: 'noredirect'
      VIRTUAL_HOST: 'bayesapi.probcomp.dev'
      VIRTUAL_PORT: 5000
    volumes:
      - .:/app:cached
    ports:
      - "5000:5000"
