version: "3"
networks:
  nginx_probcomp:
    external:
      name: nginx_probcomp

services:
  app:
    build: .
    networks:
      default:
      nginx_probcomp:
        aliases:
          - bayesapi
    volumes:
      - .:/app:cached
    ports:
      - "5000:5000"
