version: "3"
volumes:
  dhparam:
    driver: local

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:0.6.0
    environment:
      CERT_NAME: probcomp.dev
      DEFAULT_HOST: bayesrest.probcomp.dev
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - dhparam:/etc/nginx/dhparam:rw
      - ./certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
  app:
    build: .
    environment:
      HTTPS_METHOD: 'noredirect'
      VIRTUAL_HOST: 'bayesrest.probcomp.dev'
      VIRTUAL_PORT: 5000
    ports:
      - 5000:5000
    volumes:
      - .:/app:cached
