version: "3"
networks:
  nginx_probcomp:
    external:
      name: nginx_probcomp
volumes:
  dhparam:
    driver: local

services:
  app:
    build: .
    networks:
      default:
      nginx_probcomp:
        aliases:
          - bayesrest
    environment:
      HTTPS_METHOD: 'noredirect'
      VIRTUAL_HOST: 'bayesrest.probcomp.dev'
      VIRTUAL_PORT: 5000
    volumes:
      - .:/app:cached
    command: start.sh python app.py database.bdb
