version: "3"
networks:
  nginx_probcomp:
    external:
      name: nginx_probcomp

services:
  app:
    build: .
    networks:
      default:
      nginx_probcomp:
        aliases:
          - bayesrest
    user: root
    environment:
      HTTPS_METHOD: 'noredirect'
      VIRTUAL_HOST: 'bayesrest.probcomp.dev'
      VIRTUAL_PORT: 5000
      CONFIG_FILE_PATH: '/path/to/config.yaml'
    volumes:
      - .:/app:cached
    ports:
      - "5000:5000"
